spring:
  config:
    activate:
      on-profile: staging
  
  datasource:
    url: jdbc:h2:file:./data/tracker_staging;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.hivel.employee_performance_tracker: INFO
