-- =====================================================
-- V1__init_schema.sql — Employee Performance Tracker
-- =====================================================

-- 1. Employees
CREATE TABLE employees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    department  VARCHAR(100)  NOT NULL,
    role        VARCHAR(100)  NOT NULL,
    joining_date DATE         NOT NULL
);

CREATE INDEX idx_employees_department   ON employees (department);
CREATE INDEX idx_employees_joining_date ON employees (joining_date);

-- 2. Review Cycles
CREATE TABLE review_cycles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,

    CONSTRAINT chk_cycle_dates CHECK (end_date >= start_date)
);

-- 3. Performance Reviews
CREATE TABLE performance_reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT    NOT NULL,
    review_cycle_id BIGINT    NOT NULL,
    rating          INT       NOT NULL,
    reviewer_notes  TEXT,
    submitted_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_employee    FOREIGN KEY (employee_id)     REFERENCES employees (id),
    CONSTRAINT fk_review_cycle       FOREIGN KEY (review_cycle_id) REFERENCES review_cycles (id),
    CONSTRAINT chk_rating            CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_employee_cycle     UNIQUE (employee_id, review_cycle_id)
);

CREATE INDEX idx_review_employee     ON performance_reviews (employee_id);
CREATE INDEX idx_review_cycle        ON performance_reviews (review_cycle_id);

-- 4. Goals
CREATE TABLE goals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL,
    review_cycle_id BIGINT       NOT NULL,
    title           VARCHAR(500) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'pending',

    CONSTRAINT fk_goal_employee  FOREIGN KEY (employee_id)     REFERENCES employees (id),
    CONSTRAINT fk_goal_cycle     FOREIGN KEY (review_cycle_id) REFERENCES review_cycles (id),
    CONSTRAINT chk_goal_status   CHECK (status IN ('pending', 'completed', 'missed'))
);

CREATE INDEX idx_goal_employee ON goals (employee_id);
CREATE INDEX idx_goal_cycle    ON goals (review_cycle_id);
CREATE INDEX idx_goal_status   ON goals (status);
